replicaCount: 1

image:
  repository: cozyruiz/intranet-php
  tag: "1.3"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

monitoring:
  enabled: false

ingress:
  enabled: true
  className: nginx
  host: intranet.local