replicaCount: 1

appEnv: "PROD"

image:
  tag: "1.8"

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  tls:
    - secretName: escalante-wildcard-tls
      hosts:
        - intranet-php-prod.escalante.com.mx
  host: intranet-php-prod.escalante.com.mx

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60

monitoring:
  enabled: true
