name: CI-CD Pipeline

on:
  push:
    branches:
      - dev
      - main

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: cozyruiz/intranet-php

jobs:

  # =========================
  # CI - Build & Push Image
  # =========================
  build:
    runs-on: self-hosted

    outputs:
      image_tag: ${{ steps.meta.outputs.tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Eliminar metadatos de macOS
        run: |
          find "$GITHUB_WORKSPACE" -type f -name '._*' -delete
          find "$GITHUB_WORKSPACE" -type f -name '.DS_Store' -delete

      - name: Set image tag
        id: meta
        run: echo "tag=${GITHUB_SHA}" >> $GITHUB_OUTPUT
        #run: printf 'tag=%s\n' "$GITHUB_SHA" >> "$GITHUB_OUTPUT"

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Image
        run: |
          docker build -t $IMAGE_NAME:${{ steps.meta.outputs.tag }} -f docker/Dockerfile .

      - name: Push Image
        run: |
          docker push $IMAGE_NAME:${{ steps.meta.outputs.tag }}

  # =========================
  # CD - Deploy to DEV
  # =========================
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    needs: build
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

       name: Configurar Helm
        uses: azure/setup-helm@v5
        with:
          version: v3.18.4

      - name: Verificar Helm
        run: helm version

      - name: Configurar acceso a Kubernetes
        run: |
          export KUBECONFIG="${KUBECONFIG:-$HOME/.kube/config}"
          if [[ ! -f "$KUBECONFIG" ]]; then
            echo "No se encontró el kubeconfig en $KUBECONFIG"
            exit 1
          fi
          echo "KUBECONFIG=$KUBECONFIG" >> "$GITHUB_ENV"
          kubectl config current-context
          kubectl cluster-info

      - name: Ensure ingress-nginx is installed
        run: |
          if ! kubectl get deployment ingress-nginx-controller -n ingress-nginx >/dev/null 2>&1; then
            kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/cloud/deploy.yaml
          fi
          kubectl wait --namespace ingress-nginx \
            --for=condition=ready pod \
            --selector=app.kubernetes.io/component=controller \
            --timeout=120s
          kubectl get pods,svc,ingress -A

      - name: Deploy with Helm (DEV)
        run: |
          helm upgrade --install intranet-php-dev ./helm/intranet-php \
            -f helm/intranet-php/values-dev.yaml \
            --set image.tag=${{ needs.build.outputs.image_tag }}

  # =========================
  # CD - Deploy to PROD
  # =========================
  deploy-prod:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: self-hosted
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

       name: Configurar Helm
        uses: azure/setup-helm@v5
        with:
          version: v3.18.4

      - name: Verificar Helm
        run: helm version

      - name: Configurar acceso a Kubernetes
        run: |
          export KUBECONFIG="${KUBECONFIG:-$HOME/.kube/config}"
          if [[ ! -f "$KUBECONFIG" ]]; then
            echo "No se encontró el kubeconfig en $KUBECONFIG"
            exit 1
          fi
          echo "KUBECONFIG=$KUBECONFIG" >> "$GITHUB_ENV"
          kubectl config current-context
          kubectl cluster-info

      - name: Ensure ingress-nginx is installed
        run: |
          if ! kubectl get deployment ingress-nginx-controller -n ingress-nginx >/dev/null 2>&1; then
            kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/cloud/deploy.yaml
          fi
          kubectl wait --namespace ingress-nginx \
            --for=condition=ready pod \
            --selector=app.kubernetes.io/component=controller \
            --timeout=120s
          kubectl get pods,svc,ingress -A

      - name: Deploy with Helm (PROD)
        run: |
          helm upgrade --install intranet-php-prod ./helm/intranet-php \
            -f helm/intranet-php/values-prod.yaml \
            --set image.tag=${{ needs.build.outputs.image_tag }}